version: '3.10'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=test # postgres db is created by default
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./docker-postgres-multi-db.sh:/docker-entrypoint-initdb.d/docker-postgres-multi-db.sh

  whitebox:
    profiles: [ 'whitebox' ]
    build:
      context: .
      dockerfile: Dockerfile.whitebox
    restart: unless-stopped
    environment:
      - APP_NAME=Whitebox | Docker
      - POSTGRES_DB_URI=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - '8000:8000'
    depends_on:
      - postgres
