apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.name }}'
  labels:
    app: '{{ .Values.name }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Values.name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.name }}'
    spec:
      containers:
        - name: whitebox
          image: sqdhub/whitebox:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB_URI
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql/postgres 
