name: Release Charts

on:
  release:
    types: [published]

jobs:
  release_charts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          access-token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Extract chart version
        run: echo "CHART_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Bump chart version
        run: python ./.github/scripts/bump_chart_version.py $CHART_VERSION

      - name: Commit & Push
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout -b main
          git add .
          git commit -m "Bump chart version to $CHART_VERSION"
          git push origin main

      - name: Package whitebox chart
        run: |
          helm package -u --version ${CHART_VERSION} helm_charts/whitebox

      - name: Publish whitebox chart
        run: |
          curl --data-binary "@whitebox-${CHART_VERSION}.tgz" chartmuseum.squaredev.io/api/charts -u ${{ secrets.CHARTMUSEUM_USERNAME }}:${{ secrets.CHARTMUSEUM_PASSWORD }}
